apiVersion: v1
kind: ConfigMap
metadata:
  name: pytorch-config
  namespace: mlops-pytorch
data:
  training_config.yaml: |
    batch_size: 32
    epochs: 3
    learning_rate: 0.001
    num_classes: 10
    in_channels: 3
    image_size: 32
