apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-serving
  namespace: mlops-pytorch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pytorch-serving
  template:
    metadata:
      labels:
        app: pytorch-serving
    spec:
      containers:
        - name: serve
          image: pytorch-serving:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /tmp/model/model.pt
