apiVersion: v1
kind: Service
metadata:
  name: pytorch-serving
  namespace: mlops-pytorch
spec:
  selector:
    app: pytorch-serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
